### ISSUE TITLE
BaseGetConsoleReference not found

### ISSUE THREAD

**Issue by funnybananas** [fortra/No-Consolation#1]
Received error message when running debug version: "The address of 'BaseGetConsoleReference' was not found"

Looking at the exported functions of KernelBase.dll shows no "BaseGetConsoleReference" function. It seems that it was present on earlier versions though (after some google searching).

**Comment by funnybananas** [comment]
Hi! Very fast response lol

This error was encountered on Windows Server 2016 build 14393.

I did just see that on another system running Windows 10 build 19045 that KernelBase.dll *DOES* export BaseGetConsoleReference

**Comment by S4ntiagoP** [comment]
Ok, interesting, would you mind sharing both KernelBase.dll files? You can talk to me on Twitter if you want an email address to send them to.

**Comment by funnybananas** [comment]
shoot me a follow and i'll DM you

**Comment by funnybananas** [comment]
To follow-up, this error does not appear on Windows 10 or Windows Server 2019. So far I've only encountered it on Server 2016.

**Comment by S4ntiagoP** [comment]
Closing this, reopen if needed.
Thank you for reporting!
